spring:
  # datasource 数据源配置内容
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/caoruiqun?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    password: root

# mybatis 配置内容
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
