spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8858 # Nacos 服务器地址
#        namespace: 64a1f18e-16de-411b-b6ad-c1648a0c1aad # Nacos 命名空间 uat 的编号
